import type {
  Employee,
  AttendanceDay,
  AttendanceCorrection,
  LeaveRequest,
  LeaveBalance,
  ShiftSchedule,
  Holiday,
  PayrollPeriod,
  Payslip,
  EmployeeDocument,
  PerformanceGoal,
  AppNotification,
  Announcement,
  AuditLog,
  UserSession,
} from "../../types";

const STORAGE_KEY = "ems_2026_store_v1";

export interface EMSStoreData {
  users: UserSession[];
  employees: Employee[];
  attendance: AttendanceDay[];
  corrections: AttendanceCorrection[];
  leaveRequests: LeaveRequest[];
  leaveBalances: Record<string, LeaveBalance>; // employeeId -> balance
  schedules: ShiftSchedule[];
  holidays: Holiday[];
  payrollPeriods: PayrollPeriod[];
  payslips: Payslip[];
  documents: EmployeeDocument[];
  goals: PerformanceGoal[];
  notifications: AppNotification[];
  announcements: Announcement[];
  auditLogs: AuditLog[];
}

const DEFAULT_USERS: UserSession[] = [
  {
    id: "usr_admin",
    employeeId: "EMP001",
    name: "Vikram Malhotra",
    email: "admin@ems.company.com",
    role: "ADMIN",
    department: "Executive",
    designation: "Chief Technology Officer",
    permissions: [
      "view:own_profile",
      "edit:own_profile",
      "manage:users",
      "manage:roles",
      "view:all_employees",
      "manage:employees",
      "view:team_employees",
      "view:own_attendance",
      "view:org_attendance",
      "view:team_attendance",
      "mark:employee_attendance",
      "review:attendance_corrections",
      "manage:schedules",
      "view:schedules",
      "manage:leave_policies",
      "view:own_payslips",
      "view:employee_payroll",
      "process:payroll",
      "lock:payroll",
      "manage:documents",
      "view:own_documents",
      "manage:performance",
      "view:reports",
      "view:audit_logs",
      "manage:notifications",
      "manage:system_settings",
      "access:ai_assistant",
    ],
  },
  {
    id: "usr_hr",
    employeeId: "EMP002",
    name: "Pooja Sharma",
    email: "hr@ems.company.com",
    role: "HR",
    department: "Human Resources",
    designation: "Lead HR Business Partner",
    permissions: [
      "view:own_profile",
      "edit:own_profile",
      "view:all_employees",
      "manage:employees",
      "view:team_employees",
      "view:own_attendance",
      "view:org_attendance",
      "view:team_attendance",
      "record:own_attendance",
      "mark:employee_attendance",
      "review:attendance_corrections",
      "manage:schedules",
      "view:schedules",
      "apply:leave",
      "approve:team_leave",
      "manage:leave_policies",
      "view:own_payslips",
      "view:employee_payroll",
      "process:payroll",
      "lock:payroll",
      "manage:documents",
      "view:own_documents",
      "manage:performance",
      "view:reports",
      "view:audit_logs",
      "manage:notifications",
      "manage:system_settings",
      "access:ai_assistant",
    ],
  },
  {
    id: "usr_mgr",
    employeeId: "EMP003",
    name: "Rajesh Iyer",
    email: "manager@ems.company.com",
    role: "MANAGER",
    department: "Engineering",
    designation: "Engineering Director",
    permissions: [
      "view:own_profile",
      "edit:own_profile",
      "view:team_employees",
      "view:own_attendance",
      "view:team_attendance",
      "record:own_attendance",
      "review:attendance_corrections",
      "view:schedules",
      "apply:leave",
      "approve:team_leave",
      "view:own_payslips",
      "manage:documents",
      "view:own_documents",
      "manage:performance",
      "view:own_performance",
      "view:reports",
      "access:ai_assistant",
    ],
  },
  {
    id: "usr_emp",
    employeeId: "EMP004",
    name: "Aarav Patel",
    email: "employee@ems.company.com",
    role: "EMPLOYEE",
    department: "Engineering",
    designation: "Senior Software Engineer",
    permissions: [
      "view:own_profile",
      "edit:own_profile",
      "view:own_attendance",
      "record:own_attendance",
      "view:schedules",
      "apply:leave",
      "view:own_payslips",
      "view:own_documents",
      "view:own_performance",
      "access:ai_assistant",
    ],
  },
];

const DEFAULT_EMPLOYEES: Employee[] = [
  {
    id: "EMP001",
    employeeNumber: "EMS-1001",
    firstName: "Vikram",
    lastName: "Malhotra",
    email: "admin@ems.company.com",
    phone: "+91 98201 11223",
    department: "Executive",
    designation: "Chief Technology Officer",
    role: "ADMIN",
    status: "ACTIVE",
    joinDate: "2020-01-15",
    workMode: "HYBRID",
    salary: 2800000,
    currency: "INR",
    location: "Bengaluru HQ",
    scheduleId: "SCH01",
  },
  {
    id: "EMP002",
    employeeNumber: "EMS-1002",
    firstName: "Pooja",
    lastName: "Sharma",
    email: "hr@ems.company.com",
    phone: "+91 98402 33445",
    department: "Human Resources",
    designation: "Lead HR Business Partner",
    role: "HR",
    managerId: "EMP001",
    managerName: "Vikram Malhotra",
    status: "ACTIVE",
    joinDate: "2021-03-10",
    workMode: "OFFICE",
    salary: 1400000,
    currency: "INR",
    location: "Bengaluru HQ",
    scheduleId: "SCH01",
  },
  {
    id: "EMP003",
    employeeNumber: "EMS-1003",
    firstName: "Rajesh",
    lastName: "Iyer",
    email: "manager@ems.company.com",
    phone: "+91 97110 55667",
    department: "Engineering",
    designation: "Engineering Director",
    role: "MANAGER",
    managerId: "EMP001",
    managerName: "Vikram Malhotra",
    status: "ACTIVE",
    joinDate: "2021-07-01",
    workMode: "HYBRID",
    salary: 2200000,
    currency: "INR",
    location: "Bengaluru HQ",
    scheduleId: "SCH01",
  },
  {
    id: "EMP004",
    employeeNumber: "EMS-1004",
    firstName: "Aarav",
    lastName: "Patel",
    email: "employee@ems.company.com",
    phone: "+91 98980 77889",
    department: "Engineering",
    designation: "Senior Software Engineer",
    role: "EMPLOYEE",
    managerId: "EMP003",
    managerName: "Rajesh Iyer",
    status: "ACTIVE",
    joinDate: "2022-04-18",
    workMode: "WFH",
    salary: 1600000,
    currency: "INR",
    location: "Remote / Pune",
    scheduleId: "SCH01",
  },
  {
    id: "EMP005",
    employeeNumber: "EMS-1005",
    firstName: "Sneha",
    lastName: "Reddy",
    email: "sneha.reddy@ems.company.com",
    phone: "+91 99001 22334",
    department: "Engineering",
    designation: "Full Stack Engineer",
    role: "EMPLOYEE",
    managerId: "EMP003",
    managerName: "Rajesh Iyer",
    status: "ACTIVE",
    joinDate: "2023-01-09",
    workMode: "OFFICE",
    salary: 1100000,
    currency: "INR",
    location: "Bengaluru HQ",
    scheduleId: "SCH01",
  },
  {
    id: "EMP006",
    employeeNumber: "EMS-1006",
    firstName: "Ananya",
    lastName: "Roy",
    email: "ananya.roy@ems.company.com",
    phone: "+91 98310 44556",
    department: "Design",
    designation: "Product Designer",
    role: "EMPLOYEE",
    managerId: "EMP003",
    managerName: "Rajesh Iyer",
    status: "PROBATION",
    joinDate: "2024-06-15",
    workMode: "HYBRID",
    salary: 950000,
    currency: "INR",
    location: "Bengaluru HQ",
    scheduleId: "SCH01",
  },
  {
    id: "EMP007",
    employeeNumber: "EMS-1007",
    firstName: "Rohan",
    lastName: "Deshmukh",
    email: "rohan.deshmukh@ems.company.com",
    phone: "+91 98220 66778",
    department: "Sales",
    designation: "Account Executive",
    role: "EMPLOYEE",
    managerId: "EMP001",
    managerName: "Vikram Malhotra",
    status: "ON_LEAVE",
    joinDate: "2023-09-01",
    workMode: "OFFICE",
    salary: 800000,
    currency: "INR",
    location: "Mumbai Branch",
    scheduleId: "SCH01",
  },
];

const TODAY_STR = "2026-09-24";

const DEFAULT_SCHEDULES: ShiftSchedule[] = [
  {
    id: "SCH01",
    name: "General Morning Shift",
    startTime: "09:00",
    endTime: "18:00",
    expectedHours: 8,
    gracePeriodMinutes: 15,
    breakMinutes: 60,
    allowedWorkModes: ["OFFICE", "WFH", "HYBRID"],
    workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    assignedEmployeesCount: 6,
  },
  {
    id: "SCH02",
    name: "Evening Shift",
    startTime: "13:00",
    endTime: "22:00",
    expectedHours: 8,
    gracePeriodMinutes: 15,
    breakMinutes: 60,
    allowedWorkModes: ["OFFICE", "WFH"],
    workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    assignedEmployeesCount: 1,
  },
];

const DEFAULT_HOLIDAYS: Holiday[] = [
  {
    id: "HOL01",
    name: "Mahatma Gandhi Jayanti",
    date: "2026-10-02",
    type: "PUBLIC",
    locations: ["All Locations"],
  },
  {
    id: "HOL02",
    name: "Dussehra (Vijayadashami)",
    date: "2026-10-20",
    type: "PUBLIC",
    locations: ["All Locations"],
  },
  {
    id: "HOL03",
    name: "Diwali (Deepavali)",
    date: "2026-11-08",
    type: "PUBLIC",
    locations: ["All Locations"],
  },
  {
    id: "HOL04",
    name: "Guru Nanak Jayanti",
    date: "2026-11-24",
    type: "OPTIONAL",
    locations: ["Bengaluru HQ", "Mumbai Branch"],
  },
  {
    id: "HOL05",
    name: "Christmas Day",
    date: "2026-12-25",
    type: "PUBLIC",
    locations: ["All Locations"],
  },
];

const DEFAULT_ATTENDANCE: AttendanceDay[] = [
  {
    id: "ATT01",
    employeeId: "EMP004", // Aarav Patel
    employeeName: "Aarav Patel",
    department: "Engineering",
    date: TODAY_STR,
    schedule: { shiftName: "General Morning", start: "09:00", end: "18:00" },
    events: [
      { id: "p1", type: "CHECK_IN", timestamp: `${TODAY_STR}T09:05:00` },
      { id: "p2", type: "BREAK_START", timestamp: `${TODAY_STR}T13:00:00` },
      { id: "p3", type: "BREAK_END", timestamp: `${TODAY_STR}T13:45:00` },
    ],
    workState: "PRESENT",
    workMode: "WFH",
    punctuality: {
      isLate: false,
      lateMinutes: 0,
      isEarlyDeparture: false,
      earlyMinutes: 0,
      overtimeMinutes: 0,
    },
    workedMinutes: 380,
    scheduledMinutes: 480,
    breakMinutes: 45,
    exceptions: [],
    correctionRequested: false,
  },
  {
    id: "ATT02",
    employeeId: "EMP005", // Sneha Reddy
    employeeName: "Sneha Reddy",
    department: "Engineering",
    date: TODAY_STR,
    schedule: { shiftName: "General Morning", start: "09:00", end: "18:00" },
    events: [
      { id: "p4", type: "CHECK_IN", timestamp: `${TODAY_STR}T09:28:00` },
    ],
    workState: "PRESENT",
    workMode: "OFFICE",
    punctuality: {
      isLate: true,
      lateMinutes: 28,
      isEarlyDeparture: false,
      earlyMinutes: 0,
      overtimeMinutes: 0,
    },
    workedMinutes: 350,
    scheduledMinutes: 480,
    breakMinutes: 0,
    exceptions: ["Late Arrival (28m)"],
    correctionRequested: false,
  },
  {
    id: "ATT03",
    employeeId: "EMP006", // Ananya Roy
    employeeName: "Ananya Roy",
    department: "Design",
    date: TODAY_STR,
    schedule: { shiftName: "General Morning", start: "09:00", end: "18:00" },
    events: [],
    workState: "ABSENT",
    workMode: "OFFICE",
    punctuality: {
      isLate: false,
      lateMinutes: 0,
      isEarlyDeparture: false,
      earlyMinutes: 0,
      overtimeMinutes: 0,
    },
    workedMinutes: 0,
    scheduledMinutes: 480,
    breakMinutes: 0,
    exceptions: ["Unexcused Absence"],
    correctionRequested: false,
  },
  {
    id: "ATT04",
    employeeId: "EMP007", // Rohan Deshmukh
    employeeName: "Rohan Deshmukh",
    department: "Sales",
    date: TODAY_STR,
    schedule: { shiftName: "General Morning", start: "09:00", end: "18:00" },
    events: [],
    workState: "PARTIAL_DAY",
    workMode: "OFFICE",
    punctuality: {
      isLate: false,
      lateMinutes: 0,
      isEarlyDeparture: false,
      earlyMinutes: 0,
      overtimeMinutes: 0,
    },
    workedMinutes: 0,
    scheduledMinutes: 480,
    breakMinutes: 0,
    exceptions: ["Approved Medical Leave"],
    correctionRequested: false,
  },
  {
    id: "ATT05",
    employeeId: "EMP003", // Rajesh Iyer
    employeeName: "Rajesh Iyer",
    department: "Engineering",
    date: TODAY_STR,
    schedule: { shiftName: "General Morning", start: "09:00", end: "18:00" },
    events: [
      { id: "p5", type: "CHECK_IN", timestamp: `${TODAY_STR}T08:55:00` },
      { id: "p6", type: "CHECK_OUT", timestamp: `${TODAY_STR}T17:30:00` },
    ],
    workState: "PRESENT",
    workMode: "HYBRID",
    punctuality: {
      isLate: false,
      lateMinutes: 0,
      isEarlyDeparture: true,
      earlyMinutes: 30,
      overtimeMinutes: 0,
    },
    workedMinutes: 515,
    scheduledMinutes: 480,
    breakMinutes: 60,
    exceptions: ["Early Departure (30m)"],
    correctionRequested: false,
  },
  // Yesterday's missing checkout record for Aarav to test correction flow
  {
    id: "ATT06",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    department: "Engineering",
    date: "2026-09-23",
    schedule: { shiftName: "General Morning", start: "09:00", end: "18:00" },
    events: [{ id: "p7", type: "CHECK_IN", timestamp: "2026-09-23T09:02:00" }],
    workState: "PRESENT",
    workMode: "WFH",
    punctuality: {
      isLate: false,
      lateMinutes: 0,
      isEarlyDeparture: false,
      earlyMinutes: 0,
      overtimeMinutes: 0,
    },
    workedMinutes: 480,
    scheduledMinutes: 480,
    breakMinutes: 60,
    exceptions: ["Missing Checkout"],
    correctionRequested: true,
    correctionId: "COR01",
  },
];

const DEFAULT_CORRECTIONS: AttendanceCorrection[] = [
  {
    id: "COR01",
    attendanceId: "ATT06",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    date: "2026-09-23",
    originalPunch: { checkIn: "09:02 AM" },
    requestedPunch: { checkIn: "09:02 AM", checkOut: "06:15 PM" },
    reason:
      "Internet router rebooted right at end of shift; forgot to punch out after reconnecting.",
    status: "PENDING",
    submittedAt: "2026-09-24T08:30:00",
  },
];

const DEFAULT_LEAVE_BALANCES: Record<string, LeaveBalance> = {
  EMP001: {
    annual: { total: 18, used: 2, available: 16 },
    casual: { total: 12, used: 1, available: 11 },
    sick: { total: 10, used: 0, available: 10 },
    unpaid: 0,
  },
  EMP002: {
    annual: { total: 18, used: 4, available: 14 },
    casual: { total: 12, used: 2, available: 10 },
    sick: { total: 10, used: 1, available: 9 },
    unpaid: 0,
  },
  EMP003: {
    annual: { total: 18, used: 5, available: 13 },
    casual: { total: 12, used: 3, available: 9 },
    sick: { total: 10, used: 2, available: 8 },
    unpaid: 0,
  },
  EMP004: {
    annual: { total: 18, used: 3, available: 15 },
    casual: { total: 12, used: 2, available: 10 },
    sick: { total: 10, used: 1, available: 9 },
    unpaid: 0,
  },
};

const DEFAULT_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: "LR01",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    department: "Engineering",
    leaveType: "CASUAL",
    startDate: "2026-10-05",
    endDate: "2026-10-06",
    daysCount: 2,
    isHalfDay: false,
    reason: "Attending cousin's wedding ceremony in Ahmedabad.",
    status: "PENDING",
    appliedAt: "2026-09-22T10:15:00",
  },
  {
    id: "LR02",
    employeeId: "EMP005",
    employeeName: "Sneha Reddy",
    department: "Engineering",
    leaveType: "SICK",
    startDate: "2026-09-18",
    endDate: "2026-09-18",
    daysCount: 1,
    isHalfDay: false,
    reason: "Severe viral fever and physician consultation.",
    status: "APPROVED",
    appliedAt: "2026-09-17T18:00:00",
    approvedBy: "Rajesh Iyer",
    approverComment: "Take care and rest well.",
  },
  {
    id: "LR03",
    employeeId: "EMP007",
    employeeName: "Rohan Deshmukh",
    department: "Sales",
    leaveType: "ANNUAL",
    startDate: TODAY_STR,
    endDate: "2026-09-26",
    daysCount: 3,
    isHalfDay: false,
    reason: "Pre-planned personal annual leave.",
    status: "APPROVED",
    appliedAt: "2026-09-15T11:00:00",
    approvedBy: "Pooja Sharma",
    approverComment: "Approved as per leave balance.",
  },
];

const DEFAULT_PAYROLL_PERIODS: PayrollPeriod[] = [
  {
    id: "PAY-2026-09",
    period: "2026-09",
    name: "September 2026",
    startDate: "2026-09-01",
    endDate: "2026-09-30",
    status: "REVIEW",
    totalGross: 9850000,
    totalDeductions: 145000,
    totalNet: 9705000,
    employeeCount: 7,
    exceptionsCount: 3,
  },
  {
    id: "PAY-2026-08",
    period: "2026-08",
    name: "August 2026",
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    status: "PUBLISHED",
    totalGross: 9850000,
    totalDeductions: 88000,
    totalNet: 9762000,
    employeeCount: 7,
    exceptionsCount: 0,
  },
];

const DEFAULT_PAYSLIPS: Payslip[] = [
  {
    id: "SLIP-09-EMP004",
    periodId: "PAY-2026-09",
    periodName: "September 2026",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    department: "Engineering",
    designation: "Senior Software Engineer",
    joinDate: "2022-04-18",
    panNumber: "ABCDE1234F",
    bankAccount: "HDFC **** 8821",
    payDate: "2026-09-30",
    basicSalary: 66667,
    hra: 33333,
    allowances: 33333,
    grossPay: 133333,
    leaveDeductions: 0,
    taxDeduction: 12000,
    pfDeduction: 8000,
    totalDeductions: 20000,
    netPay: 113333,
    status: "PAID",
    attendanceSummary: {
      totalDays: 30,
      presentDays: 22,
      absentDays: 0,
      halfDays: 0,
      wfhDays: 22,
      paidLeavesUsed: 0,
      unpaidLeaves: 0,
    },
  },
  {
    id: "SLIP-08-EMP004",
    periodId: "PAY-2026-08",
    periodName: "August 2026",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    department: "Engineering",
    designation: "Senior Software Engineer",
    joinDate: "2022-04-18",
    panNumber: "ABCDE1234F",
    bankAccount: "HDFC **** 8821",
    payDate: "2026-08-31",
    basicSalary: 66667,
    hra: 33333,
    allowances: 33333,
    grossPay: 133333,
    leaveDeductions: 0,
    taxDeduction: 12000,
    pfDeduction: 8000,
    totalDeductions: 20000,
    netPay: 113333,
    status: "PAID",
    attendanceSummary: {
      totalDays: 31,
      presentDays: 22,
      absentDays: 0,
      halfDays: 0,
      wfhDays: 22,
      paidLeavesUsed: 0,
      unpaidLeaves: 0,
    },
  },
];

const DEFAULT_DOCUMENTS: EmployeeDocument[] = [
  {
    id: "DOC01",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    name: "Employment_Agreement_Signed.pdf",
    category: "CONTRACT",
    fileSize: "2.4 MB",
    uploadedAt: "2022-04-18",
    status: "VALID",
  },
  {
    id: "DOC02",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    name: "Aadhaar_National_ID.pdf",
    category: "ID_PROOF",
    fileSize: "1.1 MB",
    uploadedAt: "2022-04-19",
    status: "VALID",
  },
  {
    id: "DOC03",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    name: "AWS_Certified_Solutions_Architect.pdf",
    category: "CERTIFICATE",
    fileSize: "850 KB",
    uploadedAt: "2023-08-10",
    expiryDate: "2026-11-15",
    status: "EXPIRING_SOON",
  },
];

const DEFAULT_GOALS: PerformanceGoal[] = [
  {
    id: "G01",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    title: "Migrate Microservice Architecture to Kubernetes",
    description:
      "Containerize existing backend microservices and configure Helm charts with zero downtime.",
    targetDate: "2026-10-31",
    progress: 75,
    status: "ON_TRACK",
    reviewerFeedback: "Excellent progress on staging environment testing.",
  },
  {
    id: "G02",
    employeeId: "EMP004",
    employeeName: "Aarav Patel",
    title: "Implement Realtime Telemetry Pipeline",
    description:
      "Deliver low-latency workforce telemetry burst detection and realtime attendance ingestion.",
    targetDate: "2026-09-30",
    progress: 95,
    status: "COMPLETED",
    reviewerFeedback: "Hardware testing verified successfully on client kiosk.",
  },
];

const DEFAULT_NOTIFICATIONS: AppNotification[] = [
  {
    id: "N01",
    title: "Leave Request Submitted",
    message:
      "Your casual leave request for Oct 05-06 has been submitted for manager review.",
    type: "LEAVE",
    read: false,
    createdAt: "2026-09-24T08:35:00",
    targetUrl: "/my-leave",
    priority: "NORMAL",
  },
  {
    id: "N02",
    title: "Attendance Correction Pending",
    message: "Correction for Sep 23 punch-out is awaiting HR approval.",
    type: "ATTENDANCE",
    read: false,
    createdAt: "2026-09-24T08:31:00",
    targetUrl: "/my-attendance",
    priority: "NORMAL",
  },
  {
    id: "N03",
    title: "August 2026 Payslip Available",
    message:
      "Your monthly payslip for August 2026 is published and ready for download.",
    type: "PAYROLL",
    read: true,
    createdAt: "2026-09-01T09:00:00",
    targetUrl: "/my-payslips",
    priority: "NORMAL",
  },
];

const DEFAULT_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ANN01",
    title: "Upcoming Holiday: Mahatma Gandhi Jayanti",
    content:
      "Please note that company offices will be closed on Friday, October 2nd, 2026 in observance of Mahatma Gandhi Jayanti. Enjoy the long weekend!",
    author: "Pooja Sharma (Lead HR)",
    targetRole: "ALL",
    priority: "HOLIDAY",
    createdAt: "2026-09-20T10:00:00",
  },
  {
    id: "ANN02",
    title: "Q3 Performance Review Cycle Kickoff",
    content:
      "Managers and employees are requested to submit self-evaluations and goal progress by October 15th, 2026.",
    author: "Vikram Malhotra (CTO)",
    targetRole: "ALL",
    priority: "GENERAL",
    createdAt: "2026-09-18T14:30:00",
  },
];

const DEFAULT_AUDIT_LOGS: AuditLog[] = [
  {
    id: "AUD01",
    timestamp: "2026-09-24 08:30:00",
    action: "ATTENDANCE_CORRECTION_SUBMIT",
    resource: "AttendanceDay: ATT06",
    user: "employee@ems.company.com",
    role: "EMPLOYEE",
    status: "SUCCESS",
    details: "Submitted checkout correction for 2026-09-23",
  },
  {
    id: "AUD02",
    timestamp: "2026-09-23 18:00:00",
    action: "LEAVE_APPROVAL",
    resource: "LeaveRequest: LR02",
    user: "manager@ems.company.com",
    role: "MANAGER",
    status: "SUCCESS",
    details: "Approved sick leave for Sneha Reddy",
  },
  {
    id: "AUD03",
    timestamp: "2026-09-22 10:15:00",
    action: "LEAVE_APPLY",
    resource: "LeaveRequest: LR01",
    user: "employee@ems.company.com",
    role: "EMPLOYEE",
    status: "SUCCESS",
    details: "Applied for 2 days Casual Leave",
  },
  {
    id: "AUD04",
    timestamp: "2026-09-20 16:45:00",
    action: "PAYROLL_REVIEW_START",
    resource: "PayrollPeriod: PAY-2026-09",
    user: "hr@ems.company.com",
    role: "HR",
    status: "SUCCESS",
    details: "Initiated September 2026 payroll review run",
  },
];

export function getStore(): EMSStoreData {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      return JSON.parse(raw);
    }
  } catch (e) {
    console.error("Failed to load EMS store from localStorage", e);
  }
  // Initialize default
  const defaultData: EMSStoreData = {
    users: DEFAULT_USERS,
    employees: DEFAULT_EMPLOYEES,
    attendance: DEFAULT_ATTENDANCE,
    corrections: DEFAULT_CORRECTIONS,
    leaveRequests: DEFAULT_LEAVE_REQUESTS,
    leaveBalances: DEFAULT_LEAVE_BALANCES,
    schedules: DEFAULT_SCHEDULES,
    holidays: DEFAULT_HOLIDAYS,
    payrollPeriods: DEFAULT_PAYROLL_PERIODS,
    payslips: DEFAULT_PAYSLIPS,
    documents: DEFAULT_DOCUMENTS,
    goals: DEFAULT_GOALS,
    notifications: DEFAULT_NOTIFICATIONS,
    announcements: DEFAULT_ANNOUNCEMENTS,
    auditLogs: DEFAULT_AUDIT_LOGS,
  };
  saveStore(defaultData);
  return defaultData;
}

export function saveStore(data: EMSStoreData): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch (e) {
    console.error("Failed to save EMS store to localStorage", e);
  }
}
